import Head from 'next/head';
import Link from 'next/link';
import styles from './home.module.scss';

export default function Home() {
  return (
    <>
      <Head>
        <title>Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.gstatic.com" />
        <link
          href="https://fonts.googleapis.com/css2?family=Roboto&display=swap"
          rel="stylesheet"
        />
      </Head>

      <main>
        <div className={styles.main}>
          <div className={styles.image}>
            <img src="/profile.jpg" alt="Imagem de perfl" />
          </div>

          <h2>Guilherme Santana</h2>

          <h1>Desenvoldedor Front End</h1>
        </div>

        <div className={styles.link}>
          <Link href="https://github.com/guisantanaa">
            <a className={styles.a} target="_blank">
              Github
            </a>
          </Link>

          <Link href="https://www.linkedin.com/in/guilhermesantanaa/">
            <a className={styles.a} target="_blank">
              LinkedIn
            </a>
          </Link>
        </div>
      </main>
    </>
  );
}
